-- CREATE THE DATABASE FOR THE LIBRARY MANAGEMENT SYSTEM
-- LMS LIBRARY MANAGEMENT SYSTEM
CREATE DATABASE LMS;

-- SWITCH TO THE NEWLY CREATED DATABASE
USE LMS;

-- CREATE THE STUDENTS TABLE
CREATE TABLE STUDENTS (
	STUDENT_ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) UNIQUE NOT NULL,
	BOOKS_BORROWED INT DEFAULT 0 CHECK (BOOKS_BORROWED <= 6),
	FINES DECIMAL(6, 2) DEFAULT 0.00
);


-- CREATE THE FACULTIES TABLE
CREATE TABLE FACULTIES (
	FACULTY_ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	EMAIL VARCHAR(100) UNIQUE NOT NULL,
	BOOKS_BORROWED INT DEFAULT 0 CHECK (BOOKS_BORROWED <- 18),
	FINES DECIMAL(6, 2) DEFAULT 0.00
);

-- CREATE THE BOOKS TABLE
CREATE TABLE BOOKS (
	BOOK_ID INT PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	AUTHOR VARCHAR(100) NOT NULL,
	STOCK INT NOT NULL DEFAULT 0
);

-- CREATE A TABLE TO STORE THE BOOK BORROWINGS
CREATE TABLE BOOK_BORROWINGS (
	BORROWING_ID INT PRIMARY KEY AUTO_INCREMENT,
	BOOK_ID INT NOT NULL,
	BORROWER_ID INT NOT NULL,
	BORROWER_TYPE ENUM('STUDENT', 'FACULTY') NOT NULL,
	BORROWED_DATE DATE NOT NULL,
	DUE_DATE DATE NOT NULL,
	RETURNED_DATE DATE,
	FINE_AMOUNT DECIMAL(6, 2) DEFAULT 0.00,
	FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (BOOK_ID),
	FOREIGN KEY (BORROWER_ID) REFERENCES STUDENTS (STUDENT_ID) ON DELETE CASCADE,
	FOREIGN KEY (BORROWER_ID) REFERENCES FACULTIES (FACULTY_ID) ON DELETE CASCADE
);
